# Generated by Django 3.2.8 on 2023-01-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, default='', null=True)),
            ],
        ),
    ]
